///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/musica_principal.aks
/// Generation time: mar nov  3 22:29:53 CET 2020
///

/// Song 'song_principal' metadata macros
#define song_principal_address  0x0040
#define song_principal_size     246
#define song_principal_end      0x135

/// Song 'song_principal' array declaration
extern void song_principal[song_principal_size];
